module.exports = function(karma) {
    karma.set({
        // base path, that will be used to resolve files and exclude
        basePath: '../',

        // list of files / patterns to load in the browser
        files: [
            'bower_components/openlayers/lib/OpenLayers.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Class.js',
            'bower_components/openlayers/lib/OpenLayers/Util.js',
            'bower_components/openlayers/lib/OpenLayers/Animation.js',
            'bower_components/openlayers/lib/OpenLayers/Util/vendorPrefix.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Bounds.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Date.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Element.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/LonLat.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Pixel.js',
            'bower_components/openlayers/lib/OpenLayers/BaseTypes/Size.js',
            'bower_components/openlayers/lib/OpenLayers/Console.js',
            'bower_components/openlayers/lib/OpenLayers/Tween.js',
            'bower_components/openlayers/lib/OpenLayers/Kinetic.js',
            'bower_components/openlayers/lib/OpenLayers/Events.js',
            'bower_components/openlayers/lib/OpenLayers/Events/buttonclick.js',
            'bower_components/openlayers/lib/OpenLayers/Events/featureclick.js',
            'bower_components/openlayers/lib/OpenLayers/Request.js',
            'bower_components/openlayers/lib/OpenLayers/Request/XMLHttpRequest.js',
            'bower_components/openlayers/lib/OpenLayers/Projection.js',
            'bower_components/openlayers/lib/OpenLayers/Map.js',
            'bower_components/openlayers/lib/OpenLayers/Layer.js',
            'bower_components/openlayers/lib/OpenLayers/Icon.js',
            'bower_components/openlayers/lib/OpenLayers/Marker.js',
            'bower_components/openlayers/lib/OpenLayers/Marker/Box.js',
            'bower_components/openlayers/lib/OpenLayers/Popup.js',
            'bower_components/openlayers/lib/OpenLayers/Tile.js',
            'bower_components/openlayers/lib/OpenLayers/Tile/Image.js',
            'bower_components/openlayers/lib/OpenLayers/Tile/Image/IFrame.js',
            'bower_components/openlayers/lib/OpenLayers/Tile/UTFGrid.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Image.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/SphericalMercator.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/EventPane.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/FixedZoomLevels.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Google.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Google/v3.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/HTTPRequest.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Grid.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/MapGuide.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/MapServer.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/KaMap.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/KaMapCache.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Markers.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Text.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/WorldWind.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/ArcGIS93Rest.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/WMS.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/WMTS.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/ArcIMS.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/GeoRSS.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Boxes.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/XYZ.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/UTFGrid.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/OSM.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Bing.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/TMS.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/TileCache.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Zoomify.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/ArcGISCache.js',
            'bower_components/openlayers/lib/OpenLayers/Popup/Anchored.js',
            'bower_components/openlayers/lib/OpenLayers/Popup/Framed.js',
            'bower_components/openlayers/lib/OpenLayers/Popup/FramedCloud.js',
            'bower_components/openlayers/lib/OpenLayers/Feature.js',
            'bower_components/openlayers/lib/OpenLayers/Feature/Vector.js',
            'bower_components/openlayers/lib/OpenLayers/Handler.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Click.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Hover.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Point.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Path.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Polygon.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Feature.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Drag.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Pinch.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/RegularPolygon.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Box.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/MouseWheel.js',
            'bower_components/openlayers/lib/OpenLayers/Handler/Keyboard.js',
            'bower_components/openlayers/lib/OpenLayers/Control.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Attribution.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Button.js',
            'bower_components/openlayers/lib/OpenLayers/Control/CacheRead.js',
            'bower_components/openlayers/lib/OpenLayers/Control/CacheWrite.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ZoomBox.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ZoomToMaxExtent.js',
            'bower_components/openlayers/lib/OpenLayers/Control/DragPan.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Navigation.js',
            'bower_components/openlayers/lib/OpenLayers/Control/PinchZoom.js',
            'bower_components/openlayers/lib/OpenLayers/Control/TouchNavigation.js',
            'bower_components/openlayers/lib/OpenLayers/Control/MousePosition.js',
            'bower_components/openlayers/lib/OpenLayers/Control/OverviewMap.js',
            'bower_components/openlayers/lib/OpenLayers/Control/KeyboardDefaults.js',
            'bower_components/openlayers/lib/OpenLayers/Control/PanZoom.js',
            'bower_components/openlayers/lib/OpenLayers/Control/PanZoomBar.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ArgParser.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Permalink.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Scale.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ScaleLine.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Snapping.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Split.js',
            'bower_components/openlayers/lib/OpenLayers/Control/LayerSwitcher.js',
            'bower_components/openlayers/lib/OpenLayers/Control/DrawFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/DragFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ModifyFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Panel.js',
            'bower_components/openlayers/lib/OpenLayers/Control/SelectFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/NavigationHistory.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Measure.js',
            'bower_components/openlayers/lib/OpenLayers/Control/WMSGetFeatureInfo.js',
            'bower_components/openlayers/lib/OpenLayers/Control/WMTSGetFeatureInfo.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Graticule.js',
            'bower_components/openlayers/lib/OpenLayers/Control/TransformFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/UTFGrid.js',
            'bower_components/openlayers/lib/OpenLayers/Control/SLDSelect.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Zoom.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/Collection.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/Point.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/MultiPoint.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/Curve.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/LineString.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/LinearRing.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/Polygon.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/MultiLineString.js',
            'bower_components/openlayers/lib/OpenLayers/Geometry/MultiPolygon.js',
            'bower_components/openlayers/lib/OpenLayers/Renderer.js',
            'bower_components/openlayers/lib/OpenLayers/Renderer/Elements.js',
            'bower_components/openlayers/lib/OpenLayers/Renderer/SVG.js',
            'bower_components/openlayers/lib/OpenLayers/Renderer/Canvas.js',
            'bower_components/openlayers/lib/OpenLayers/Renderer/VML.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Vector.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/PointGrid.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/Vector/RootContainer.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Filter.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Fixed.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Cluster.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Paging.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/BBOX.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Save.js',
            'bower_components/openlayers/lib/OpenLayers/Strategy/Refresh.js',
            'bower_components/openlayers/lib/OpenLayers/Filter.js',
            'bower_components/openlayers/lib/OpenLayers/Filter/FeatureId.js',
            'bower_components/openlayers/lib/OpenLayers/Filter/Logical.js',
            'bower_components/openlayers/lib/OpenLayers/Filter/Comparison.js',
            'bower_components/openlayers/lib/OpenLayers/Filter/Spatial.js',
            'bower_components/openlayers/lib/OpenLayers/Filter/Function.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/HTTP.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/WFS.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/WFS/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/WFS/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/WFS/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/CSW.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/CSW/v2_0_2.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/Script.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/SOS.js',
            'bower_components/openlayers/lib/OpenLayers/Protocol/SOS/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Layer/PointTrack.js',
            'bower_components/openlayers/lib/OpenLayers/Style.js',
            'bower_components/openlayers/lib/OpenLayers/Style2.js',
            'bower_components/openlayers/lib/OpenLayers/StyleMap.js',
            'bower_components/openlayers/lib/OpenLayers/Rule.js',
            'bower_components/openlayers/lib/OpenLayers/Format.js',
            'bower_components/openlayers/lib/OpenLayers/Format/QueryStringFilter.js',
            'bower_components/openlayers/lib/OpenLayers/Format/XML.js',
            'bower_components/openlayers/lib/OpenLayers/Format/XML/VersionedOGC.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Context.js',
            'bower_components/openlayers/lib/OpenLayers/Format/ArcXML.js',
            'bower_components/openlayers/lib/OpenLayers/Format/ArcXML/Features.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GML.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GML/Base.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GML/v2.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GML/v3.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Atom.js',
            'bower_components/openlayers/lib/OpenLayers/Format/EncodedPolyline.js',
            'bower_components/openlayers/lib/OpenLayers/Format/KML.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GeoRSS.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFS.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSCommon.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSCommon/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSCommon/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSCommon/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WCSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WCSCapabilities/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WCSCapabilities/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WCSCapabilities/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFSCapabilities/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFSCapabilities/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFSCapabilities/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFSDescribeFeatureType.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSDescribeLayer.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSDescribeLayer/v1_1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WKT.js',
            'bower_components/openlayers/lib/OpenLayers/Format/CQL.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OSM.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GPX.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Filter.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Filter/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Filter/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Filter/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SLD.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SLD/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SLD/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SLD/v1_0_0_GeoServer.js',
            'bower_components/openlayers/lib/OpenLayers/Format/CSWGetDomain.js',
            'bower_components/openlayers/lib/OpenLayers/Format/CSWGetDomain/v2_0_2.js',
            'bower_components/openlayers/lib/OpenLayers/Format/CSWGetRecords.js',
            'bower_components/openlayers/lib/OpenLayers/Format/CSWGetRecords/v2_0_2.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFST.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFST/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFST/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WFST/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/Text.js',
            'bower_components/openlayers/lib/OpenLayers/Format/JSON.js',
            'bower_components/openlayers/lib/OpenLayers/Format/GeoJSON.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMC.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMC/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMC/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMC/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WCSGetCoverage.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_3.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_3_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSCapabilities/v1_1_1_WMSC.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMSGetFeatureInfo.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SOSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SOSCapabilities/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SOSGetFeatureOfInterest.js',
            'bower_components/openlayers/lib/OpenLayers/Format/SOSGetObservation.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSContext.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OWSContext/v0_3_1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMTSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WMTSCapabilities/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WPSCapabilities.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WPSCapabilities/v1_0_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WPSDescribeProcess.js',
            'bower_components/openlayers/lib/OpenLayers/Format/WPSExecute.js',
            'bower_components/openlayers/lib/OpenLayers/Format/XLS.js',
            'bower_components/openlayers/lib/OpenLayers/Format/XLS/v1.js',
            'bower_components/openlayers/lib/OpenLayers/Format/XLS/v1_1_0.js',
            'bower_components/openlayers/lib/OpenLayers/Format/OGCExceptionReport.js',
            'bower_components/openlayers/lib/OpenLayers/Control/GetFeature.js',
            'bower_components/openlayers/lib/OpenLayers/Control/NavToolbar.js',
            'bower_components/openlayers/lib/OpenLayers/Control/PanPanel.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Pan.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ZoomIn.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ZoomOut.js',
            'bower_components/openlayers/lib/OpenLayers/Control/ZoomPanel.js',
            'bower_components/openlayers/lib/OpenLayers/Control/EditingToolbar.js',
            'bower_components/openlayers/lib/OpenLayers/Control/Geolocate.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer/Point.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer/Line.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer/Polygon.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer/Text.js',
            'bower_components/openlayers/lib/OpenLayers/Symbolizer/Raster.js',
            'bower_components/openlayers/lib/OpenLayers/Lang.js',
            'bower_components/openlayers/lib/OpenLayers/Lang/en.js',
            'bower_components/openlayers/lib/OpenLayers/Spherical.js',
            'bower_components/openlayers/lib/OpenLayers/TileManager.js',
            'bower_components/openlayers/lib/OpenLayers/WPSClient.js',
            'bower_components/openlayers/lib/OpenLayers/WPSProcess.js',
            'bower_components/angular/angular.js',
            'bower_components/angular-mocks/angular-mocks.js',
            'dist/angular-openlayers-directive.js',
            'test/unit/*.js',
            'bower_components/openlayers/theme/default/style.css'
        ],

        // Frameworks
        frameworks: ["jasmine"],

        // list of files to exclude
        exclude: [
        ],

        // Start these browsers, currently available:
        // - Chrome
        // - ChromeCanary
        // - Firefox
        // - Opera
        // - Safari
        // - PhantomJS
        browsers: [
            //'Firefox',
            //'Chrome',
            'PhantomJS'
        ],

        // test results reporter to use
        // possible values: dots || progress
        reporters: ['progress'],

        // web server port
        port: 9018,

        // cli runner port
        runnerPort: 9100,

        // enable / disable colors in the output (reporters and logs)
        colors: true,

        // level of logging
        // possible values: LOG_DISABLE || LOG_ERROR || LOG_WARN || LOG_INFO || LOG_DEBUG
        logLevel: karma.LOG_INFO,

        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: false,

        // Continuous Integration mode
        // if true, it capture browsers, run tests and exit
        singleRun: true
    });
};
